module.exports = {
	MODELS: 
	[
		{ id: 'atdm-0604', label: 'ATDM-0604',
			actions: [
				'input_gain_level',
				'output_level',
				'output_mute',
				'call_preset',
				'call_partial_preset'
			],
			feedbacks: [
				'phantompower',
				'lowcut',
				'aec',
				'smartmix',
				'input_maxvolume_enabled',
				'input_mute',
				'output_mute',
				'output_maxvolume_enabled',
				'output_minvolume_enabled',
			],
			variables: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
			],
			input_channels: [
				{ id: '0', label: 'Input 1'},
				{ id: '1', label: 'Input 2'},
				{ id: '2', label: 'Input 3'},
				{ id: '3', label: 'Input 4'},
				{ id: '4', label: 'Input 5'},
				{ id: '5', label: 'Input 6'},
				{ id: '10', label: 'Input ST'},
			],
			input_channels_request: [
				{ id: '0', label: 'Input 1'},
				{ id: '1', label: 'Input 2'},
				{ id: '2', label: 'Input 3'},
				{ id: '3', label: 'Input 4'},
				{ id: '4', label: 'Input 5'},
				{ id: '5', label: 'Input 6'},
				{ id: '10', label: 'Input ST'},
			],
			input_channel_sources: [
				{ id: '0', label: 'Mic'	},
				{ id: '1', label: 'Line +4 dBu'	},
				{ id: '2', label: 'Line 0 dBV' },
				{ id: '3', label: 'Line -10 dBV' },
				{ id: '4', label: 'Line -20 dBV' },
				{ id: '5', label: 'USB' },
			],
			output_channels: [
				{ id: '0', label: 'Output 1', variableId: 'output1'},
				{ id: '1', label: 'Output 2', variableId: 'output2'},
				{ id: '10', label: 'Output ST', variableId: 'outputst'},
			],
			preset_choices: [
					{ id: 1, label: 'Preset 1'},
					{ id: 2, label: 'Preset 2'},
					{ id: 3, label: 'Preset 3'},
					{ id: 4, label: 'Preset 4'},
					{ id: 5, label: 'Preset 5'},
					{ id: 6, label: 'Preset 6'}
			],
			fbs_channels: [
				{ id: '0', label: 'Output 1'},
				{ id: '1', label: 'Output 2'},
				{ id: '10', label: 'Output ST'},
			],
			fbs_processing: [
				{ id: '0', label: 'Band Setting'},
				{ id: '1', label: 'Reset'},
				{ id: '1', label: 'Copy to Output EQ'},
			],
			fbs_bands: [
				{ id: '0', label: 'Dynamics'},
				{ id: '2', label: 'Statics'},
			],
			data_request: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'level_meter',
			],
			colors: [
				{ id: '0', label: 'Green'},
				{ id: '1', label: 'Yellow'},
				{ id: '2', label: 'Brown'},
				{ id: '3', label: 'Red'},
				{ id: '4', label: 'Pink'},
				{ id: '5', label: 'Blue'},
				{ id: '6', label: 'Gray'},
				{ id: '7', label: 'Dark Gray'},
			]
		},

		{ id: 'atdm-0604a',  label: 'ATDM-0604a',
			actions: [
				'input_gain_level',
				'output_level',
				'output_mute',
				'call_preset',
				'call_partial_preset'
			],
			feedbacks: [
				'phantompower',
				'lowcut',
				'aec',
				'smartmix',
				'input_maxvolume_enabled',
				'input_mute',
				'output_mute',
				'output_maxvolume_enabled',
				'output_minvolume_enabled',
			],
			variables: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
				'open_channel_notice'
			],
			input_channels: [
				{ id: '0', label: 'Input 1', variableId: 'input1'},
				{ id: '1', label: 'Input 2', variableId: 'input2'},
				{ id: '2', label: 'Input 3', variableId: 'input3'},
				{ id: '3', label: 'Input 4', variableId: 'input4'},
				{ id: '4', label: 'Input 5', variableId: 'input5'},
				{ id: '5', label: 'Input 6', variableId: 'input6'},
				{ id: '10', label: 'Input ST', variableId: 'inputST'},
			],
			input_channels_request: [
				{ id: '0', label: 'Input 1', variableId: 'input1'},
				{ id: '1', label: 'Input 2', variableId: 'input2'},
				{ id: '2', label: 'Input 3', variableId: 'input3'},
				{ id: '3', label: 'Input 4', variableId: 'input4'},
				{ id: '4', label: 'Input 5', variableId: 'input5'},
				{ id: '5', label: 'Input 6', variableId: 'input6'},
				{ id: '10', label: 'Input ST', variableId: 'inputST'},
			],
			input_channel_sources: [
				{ id: '0', label: 'Mic'	},
				{ id: '1', label: 'Line +4 dBu'	},
				{ id: '2', label: 'Line 0 dBV' },
				{ id: '3', label: 'Line -10 dBV' },
				{ id: '4', label: 'Line -20 dBV' },
				{ id: '5', label: 'USB' },
			],
			output_channels: [
				{ id: '0', label: 'Output 1', variableId: 'output1'},
				{ id: '1', label: 'Output 2', variableId: 'output2'},
				{ id: '10', label: 'Output ST', variableId: 'outputst'},
			],
			preset_choices: [
					{ id: 1, label: 'Preset 1'},
					{ id: 2, label: 'Preset 2'},
					{ id: 3, label: 'Preset 3'},
					{ id: 4, label: 'Preset 4'},
					{ id: 5, label: 'Preset 5'},
					{ id: 6, label: 'Preset 6'}
			],
			fbs_channels: [
				{ id: '0', label: 'Output 1'},
				{ id: '1', label: 'Output 2'},
				{ id: '10', label: 'Output ST'},
			],
			fbs_processing: [
				{ id: '0', label: 'Band Setting'},
				{ id: '1', label: 'Reset'},
				{ id: '1', label: 'Copy to Output EQ'},
			],
			fbs_bands: [
				{ id: '0', label: 'Dynamics'},
				{ id: '2', label: 'Statics'},
			],
			data_request: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
			],
			colors: [
				{ id: '0', label: 'Green'},
				{ id: '1', label: 'Yellow'},
				{ id: '2', label: 'Brown'},
				{ id: '3', label: 'Red'},
				{ id: '4', label: 'Pink'},
				{ id: '5', label: 'Blue'},
				{ id: '6', label: 'Gray'},
				{ id: '7', label: 'Dark Gray'},
			]
		},

		{ id: 'atdm-1012',  label: 'ATDM-1012',
			actions: [
				'input_gain_level',
				'output_level',
				'output_mute',
				'call_preset',
				'call_partial_preset',
				'sopl',
				'sopm'
			],
			feedbacks: [
				'phantompower',
				'lowcut',
				'aec',
				'smartmix',
				'input_maxvolume_enabled',
				'input_mute',
				'output_mute',
				'output_maxvolume_enabled',
				'output_minvolume_enabled',
				'gopm'
			],
			variables: [
				'input_channel_settings',
				'sub_input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
				'open_channel_notice',
				'gopl',
				'gopm'
			],
			input_channels: [
				{ id: '0', label: 'Input 1', variableId: 'input01'},
				{ id: '1', label: 'Input 2', variableId: 'input02'},
				{ id: '2', label: 'Input 3', variableId: 'input03'},
				{ id: '3', label: 'Input 4', variableId: 'input04'},
				{ id: '4', label: 'Input 5', variableId: 'input05'},
				{ id: '5', label: 'Input 6', variableId: 'input06'},
				{ id: '6', label: 'Input 7', variableId: 'input07'},
				{ id: '7', label: 'Input 8', variableId: 'input08'},
				{ id: '8', label: 'Input 9', variableId: 'input09'},
				{ id: '9', label: 'Input 10', variableId: 'input10'},
				{ id: '10', label: 'Input ST1', variableId: 'inputST1'},
				{ id: '11', label: 'Input ST2', variableId: 'inputST2'},
				{ id: '12', label: 'Sub Input 1', variableId: 'subinput01'},
				{ id: '13', label: 'Sub Input 2', variableId: 'subinput02'},
				{ id: '14', label: 'Sub Input 3', variableId: 'subinput03'},
				{ id: '15', label: 'Sub Input 4', variableId: 'subinput04'},
				{ id: '16', label: 'Sub Input 5', variableId: 'subinput05'},
				{ id: '17', label: 'Sub Input 6', variableId: 'subinput06'},
				{ id: '18', label: 'Sub Input 7', variableId: 'subinput07'},
				{ id: '19', label: 'Sub Input 8', variableId: 'subinput08'},
			],
			input_channels_request: [
				{ id: '0', label: 'Input 1', variableId: 'input01'},
				{ id: '1', label: 'Input 2', variableId: 'input02'},
				{ id: '2', label: 'Input 3', variableId: 'input03'},
				{ id: '3', label: 'Input 4', variableId: 'input04'},
				{ id: '4', label: 'Input 5', variableId: 'input05'},
				{ id: '5', label: 'Input 6', variableId: 'input06'},
				{ id: '6', label: 'Input 7', variableId: 'input07'},
				{ id: '7', label: 'Input 8', variableId: 'input08'},
				{ id: '8', label: 'Input 9', variableId: 'input09'},
				{ id: '9', label: 'Input 10', variableId: 'input10'},
				{ id: '10', label: 'Input ST1', variableId: 'inputST1'},
				{ id: '11', label: 'Input ST2', variableId: 'inputST2'},
			],
			input_channel_sources: [
				{ id: '0', label: 'Mic'	},
				{ id: '1', label: 'Line +4 dBu'	},
				{ id: '2', label: 'Line 0 dBV' },
				{ id: '3', label: 'Line -10 dBV' },
				{ id: '4', label: 'Line -20 dBV' },
				{ id: '5', label: 'USB' },
				{ id: '6', label: 'Virtual Mic 1' },
				{ id: '7', label: 'Virtual Mic 2' },
				{ id: '9', label: 'Dante' },
			],
			sub_input_channels: [
				{ id: '0', label: 'Sub Input 1', variableId: 'subinput01'},
				{ id: '1', label: 'Sub Input 2', variableId: 'subinput02'},
				{ id: '2', label: 'Sub Input 3', variableId: 'subinput03'},
				{ id: '3', label: 'Sub Input 4', variableId: 'subinput04'},
				{ id: '4', label: 'Sub Input 5', variableId: 'subinput05'},
				{ id: '5', label: 'Sub Input 6', variableId: 'subinput06'},
				{ id: '6', label: 'Sub Input 7', variableId: 'subinput07'},
				{ id: '7', label: 'Sub Input 8', variableId: 'subinput08'},
			],
			sub_input_channel_sources: [
				{ id: '0', label: 'Off'	},
				{ id: '1', label: 'Input 1'	},
				{ id: '2', label: 'Input 2' },
				{ id: '3', label: 'Input 3' },
				{ id: '4', label: 'Input 4' },
				{ id: '5', label: 'Input 5' },
				{ id: '6', label: 'Input 6' },
				{ id: '7', label: 'Input 7' },
				{ id: '8', label: 'Input 8' },
				{ id: '9', label: 'Input 9' },
				{ id: '10', label: 'Input 10' },
				{ id: '21', label: 'Dante 1' },
				{ id: '22', label: 'Dante 2' },
				{ id: '23', label: 'Dante 3' },
				{ id: '24', label: 'Dante 4' },
				{ id: '25', label: 'Dante 5' },
				{ id: '26', label: 'Dante 6' },
				{ id: '27', label: 'Dante 7' },
				{ id: '28', label: 'Dante 8' },
				{ id: '29', label: 'Dante 9' },
				{ id: '30', label: 'Dante 10' },
				{ id: '31', label: 'Dante 11' },
				{ id: '32', label: 'Dante 12' },
				{ id: '33', label: 'Dante 13' },
				{ id: '34', label: 'Dante 14' },
				{ id: '35', label: 'Dante 15' },
				{ id: '36', label: 'Dante 16' },
				{ id: '37', label: 'Bus #' },
			],
			output_channels: [
				{ id: '0', label: 'Output 1', variableId: 'output01'},
				{ id: '1', label: 'Output 2', variableId: 'output02'},
				{ id: '2', label: 'Output 3', variableId: 'output03'},
				{ id: '3', label: 'Output 4', variableId: 'output04'},
				{ id: '4', label: 'Output 5', variableId: 'output05'},
				{ id: '5', label: 'Output 6', variableId: 'output06'},
				{ id: '6', label: 'Output 7', variableId: 'output07'},
				{ id: '7', label: 'Output 8', variableId: 'output08'},
				{ id: '8', label: 'Output ST1', variableId: 'outputst1'},
				{ id: '9', label: 'Output ST2', variableId: 'outputst2'},
			],
			preset_choices: [
					{ id: 1, label: 'Bank 1'},
					{ id: 2, label: 'Bank 2'},
					{ id: 3, label: 'Bank 3'},
					{ id: 4, label: 'Bank 4'},
					{ id: 5, label: 'Bank 5'},
					{ id: 6, label: 'Bank 6'},
					{ id: 7, label: 'Bank 7'},
					{ id: 8, label: 'Bank 8'}
			],
			fbs_channels: [
				{ id: '0', label: 'Input 1'},
				{ id: '1', label: 'Input 2'},
				{ id: '2', label: 'Input 3'},
				{ id: '3', label: 'Input 4'},
				{ id: '4', label: 'Input 5'},
				{ id: '5', label: 'Input 6'},
				{ id: '6', label: 'Input 7'},
				{ id: '7', label: 'Input 8'},
				{ id: '8', label: 'Input 9'},
				{ id: '9', label: 'Input 10'},
				{ id: '12', label: 'Output 1'},
				{ id: '13', label: 'Output 2'},
				{ id: '14', label: 'Output 3'},
				{ id: '15', label: 'Output 4'},
				{ id: '16', label: 'Output 5'},
				{ id: '17', label: 'Output 6'},
				{ id: '18', label: 'Output 7'},
				{ id: '19', label: 'Output 8'},
				{ id: '20', label: 'Output ST1'},
				{ id: '21', label: 'Output ST2'}
			],
			fbs_processing: [
				{ id: '0', label: 'Reset'},
				{ id: '1', label: 'All Static'},
				{ id: '2', label: 'Copy to EQ'},
				{ id: '3', label: 'Band Setting'},
			],
			fbs_bands: [
				{ id: '0', label: 'Off'},
				{ id: '1', label: 'On (static)'},
			],
			data_request: [
				'input_channel_settings',
				'subinput_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
				'gopl',
				'gopm'
			],
			colors: [
				{ id: '0', label: 'Green'},
				{ id: '1', label: 'Yellow'},
				{ id: '2', label: 'Brown'},
				{ id: '3', label: 'Red'},
				{ id: '4', label: 'Pink'},
				{ id: '5', label: 'Blue'},
				{ id: '6', label: 'Gray'},
				{ id: '7', label: 'Dark Gray'},
			]
		}
	]
}