module.exports = {
	MODELS: 
	[
		{ id: 'atdm-0604', label: 'ATDM-0604',
			actions: [
				'input_gain_level',
				'output_level',
				'output_mute',
				'call_preset',
				'call_partial_preset'
			],
			feedbacks: [
				'phantompower',
				'lowcut',
				'aec',
				'smartmix',
				'input_maxvolume_enabled',
				'input_mute',
				'output_mute',
				'output_maxvolume_enabled',
				'output_minvolume_enabled',
			],
			variables: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
			],
			input_channels: [
				{ id: '0', label: 'Input 1'},
				{ id: '1', label: 'Input 2'},
				{ id: '2', label: 'Input 3'},
				{ id: '3', label: 'Input 4'},
				{ id: '4', label: 'Input 5'},
				{ id: '5', label: 'Input 6'},
				{ id: '10', label: 'Input ST'},
			],
			output_channels: [
				{ id: '0', label: 'Output 1', variableId: 'output1'},
				{ id: '1', label: 'Output 2', variableId: 'output2'},
				{ id: '10', label: 'Output ST', variableId: 'outputst'},
			],
			fbs_channels: [
				{ id: '0', label: 'Output 1'},
				{ id: '1', label: 'Output 2'},
				{ id: '10', label: 'Output ST'},
			],
			fbs_processing: [
				{ id: '0', label: 'Band Setting'},
				{ id: '1', label: 'Reset'},
				{ id: '1', label: 'Copy to Output EQ'},
			],
			fbs_bands: [
				{ id: '0', label: 'Dynamics'},
				{ id: '2', label: 'Statics'},
			],
			data_request: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
			]
		},

		{ id: 'atdm-0604a',  label: 'ATDM-0604a',
			actions: [
				'input_gain_level',
				'output_level',
				'output_mute',
				'call_preset',
				'call_partial_preset'
			],
			feedbacks: [
				'phantompower',
				'lowcut',
				'aec',
				'smartmix',
				'input_maxvolume_enabled',
				'input_mute',
				'output_mute',
				'output_maxvolume_enabled',
				'output_minvolume_enabled',
			],
			variables: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
				'open_channel_notice'
			],
			input_channels: [
				{ id: '0', label: 'Input 1', variableId: 'input1'},
				{ id: '1', label: 'Input 2', variableId: 'input2'},
				{ id: '2', label: 'Input 3', variableId: 'input3'},
				{ id: '3', label: 'Input 4', variableId: 'input4'},
				{ id: '4', label: 'Input 5', variableId: 'input5'},
				{ id: '5', label: 'Input 6', variableId: 'input6'},
				{ id: '10', label: 'Input ST', variableId: 'inputST'},
			],
			output_channels: [
				{ id: '0', label: 'Output 1', variableId: 'output1'},
				{ id: '1', label: 'Output 2', variableId: 'output2'},
				{ id: '10', label: 'Output ST', variableId: 'outputst'},
			],
			fbs_channels: [
				{ id: '0', label: 'Output 1'},
				{ id: '1', label: 'Output 2'},
				{ id: '10', label: 'Output ST'},
			],
			fbs_processing: [
				{ id: '0', label: 'Band Setting'},
				{ id: '1', label: 'Reset'},
				{ id: '1', label: 'Copy to Output EQ'},
			],
			fbs_bands: [
				{ id: '0', label: 'Dynamics'},
				{ id: '2', label: 'Statics'},
			],
			data_request: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
			]
		},

		{ id: 'atdm-1012',  label: 'ATDM-1012',
			actions: [
				'input_gain_level',
				'output_level',
				'output_mute',
				'call_preset',
				'call_partial_preset'
			],
			feedbacks: [
				'phantompower',
				'lowcut',
				'aec',
				'smartmix',
				'input_maxvolume_enabled',
				'input_mute',
				'output_mute',
				'output_maxvolume_enabled',
				'output_minvolume_enabled',
			],
			variables: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
				'open_channel_notice'
			],
			input_channels: [
				{ id: '0', label: 'Input 1', variableId: 'input1'},
				{ id: '1', label: 'Input 2', variableId: 'input2'},
				{ id: '2', label: 'Input 3', variableId: 'input3'},
				{ id: '3', label: 'Input 4', variableId: 'input4'},
				{ id: '4', label: 'Input 5', variableId: 'input5'},
				{ id: '5', label: 'Input 6', variableId: 'input6'},
				{ id: '6', label: 'Input 7', variableId: 'input7'},
				{ id: '7', label: 'Input 8', variableId: 'input8'},
				{ id: '8', label: 'Input 9', variableId: 'input9'},
				{ id: '9', label: 'Input 10', variableId: 'input10'},
				{ id: '10', label: 'Input ST1', variableId: 'inputST1'},
				{ id: '11', label: 'Input ST2', variableId: 'inputST2'},
				{ id: '12', label: 'Sub Input 1', variableId: 'subinput1'},
				{ id: '13', label: 'Sub Input 2', variableId: 'subinput2'},
				{ id: '14', label: 'Sub Input 3', variableId: 'subinput3'},
				{ id: '15', label: 'Sub Input 4', variableId: 'subinput4'},
				{ id: '16', label: 'Sub Input 5', variableId: 'subinput5'},
				{ id: '17', label: 'Sub Input 6', variableId: 'subinput6'},
				{ id: '18', label: 'Sub Input 7', variableId: 'subinput7'},
				{ id: '19', label: 'Sub Input 8', variableId: 'subinput8'},
			],
			sub_input_channels: [
				{ id: '0', label: 'Sub Input 1'},
				{ id: '1', label: 'Sub Input 2'},
				{ id: '2', label: 'Sub Input 3'},
				{ id: '3', label: 'Sub Input 4'},
				{ id: '4', label: 'Sub Input 5'},
				{ id: '5', label: 'Sub Input 6'},
				{ id: '6', label: 'Sub Input 7'},
				{ id: '7', label: 'Sub Input 8'},
			],
			output_channels: [
				{ id: '0', label: 'Output 1', variableId: 'output1'},
				{ id: '1', label: 'Output 2', variableId: 'output2'},
				{ id: '2', label: 'Output 3', variableId: 'output3'},
				{ id: '3', label: 'Output 4', variableId: 'output4'},
				{ id: '4', label: 'Output 5', variableId: 'output5'},
				{ id: '5', label: 'Output 6', variableId: 'output6'},
				{ id: '6', label: 'Output 7', variableId: 'output7'},
				{ id: '7', label: 'Output 8', variableId: 'output8'},
				{ id: '8', label: 'Output ST1', variableId: 'outputst1'},
				{ id: '9', label: 'Output ST2', variableId: 'outputst2'},
			],
			fbs_channels: [
				{ id: '0', label: 'Input 1'},
				{ id: '1', label: 'Input 2'},
				{ id: '2', label: 'Input 3'},
				{ id: '3', label: 'Input 4'},
				{ id: '4', label: 'Input 5'},
				{ id: '5', label: 'Input 6'},
				{ id: '6', label: 'Input 7'},
				{ id: '7', label: 'Input 8'},
				{ id: '8', label: 'Input 9'},
				{ id: '9', label: 'Input 10'},
				{ id: '12', label: 'Output 1'},
				{ id: '13', label: 'Output 2'},
				{ id: '14', label: 'Output 3'},
				{ id: '15', label: 'Output 4'},
				{ id: '16', label: 'Output 5'},
				{ id: '17', label: 'Output 6'},
				{ id: '18', label: 'Output 7'},
				{ id: '19', label: 'Output 8'},
				{ id: '20', label: 'Output ST1'},
				{ id: '21', label: 'Output ST2'}
			],
			fbs_processing: [
				{ id: '0', label: 'Reset'},
				{ id: '1', label: 'All Static'},
				{ id: '2', label: 'Copy to EQ'},
				{ id: '3', label: 'Band Setting'},
			],
			fbs_bands: [
				{ id: '0', label: 'Off'},
				{ id: '1', label: 'On (static)'},
			],
			data_request: [
				'input_channel_settings',
				'input_gain_level',
				'output_level',
				'output_channel_settings',
				'output_mute',
				'preset_number',
				'partial_preset_number',
				'level_meter',
			]
		}
	]
}